name: tenet_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/tenet
  - packages/tenet_result
  - packages/tenet_di
  - packages/tenet_di_flutter
  - packages/tenet_rxdart
