name: tenet_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/reson
  - packages/casus
  - packages/casus_flutter
  - packages/tenet_di
  - packages/tenet_di_flutter
  - packages/tenet_rxdart
